### ISSUE TITLE
BUILD FAILURE directly after cloning due to PgnHolderTest test errors

### ISSUE THREAD

**Issue by ghost** [bhlangonijr/chesslib#21] opened 2020-04-09 16:43 UTC
I'm unable to build the project directly after cloning it because of some PgnHolder related unit tests.
```
git clone https://www.github.com/bhlangonijr/chesslib.git
cd chesslib/
mvn clean compile package install
```
Outputs:
```
Results :

Tests in error:
  testUtf8(com.github.bhlangonijr.chesslib.PgnHolderTest): Error parsing PGN[1, ]:
  testPGNLoad4(com.github.bhlangonijr.chesslib.PgnHolderTest): Error parsing PGN[1, ]:

Tests run: 44, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.043 s
[INFO] Finished at: 2020-04-09T17:34:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project chesslib: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Projects\chesslib\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by riadhe** [comment] 2020-04-10 12:20
A quick note to say that these failed test units happen only when trying to compile the project.
There's no issue when you run them directly from the test class (PgnHolderTest).

**Comment by bhlangonijr** [comment] 2020-06-30 15:10
I can't reproduce it um my local env. If anyone reading this ticket is able to reproduce it I'd appreciate (the user who filed this ticket has been deleted).

**Comment by bhlangonijr** [comment] 2020-07-05 15:50
Can't reproduce. Should be environment specific. Will close this for now as we don't have more details.

**Closed by bhlangonijr** 2020-07-05 15:50 UTC
